#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LeexTools_Example' do
  pod 'LeexTools', :path => '../'
#  pod 'AFNetworking'
#  pod 'YYCache'
  target 'LeexTools_Tests' do
    inherit! :search_paths

    
  end
end
